spring:
  application:
    name: qxmxgateway
server:
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/ #eurekaserver 的地址，默认随机后轮训
  instance:
    hostname: 127.0.0.1
    instance-id: ${hostname}:${server.port}  #向注册中心暴露服务提供者的IP和端口
    prefer-ip-address: true
zuul:
  add-host-header: true

